//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyContacts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Person_ID { get; set; }
        public string Person_FullName { get; set; }
        public string Person_Phone { get; set; }
        public string Person_Email { get; set; }
        public string Person_Address { get; set; }
        public string Person_Picture { get; set; }
    }
}
